[package]
name = "hiddibar"
version = "0.1.0"
edition = "2021"

[dependencies]
clashctl-core = "0.4.2"
clap = { version = "4.5.27", features = ["derive"] }
bytesize = "1.3.0"
serde_json = "1.0.138"
dirs = "6.0.0"
regex = "1.11.1"
